spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

mongodb:
  uri: mongodb://localhost:27017

  databases:
    metadata: metadata

server:
  port: 9094